### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by vaibhav-jain** [andrewebdev/django-adzone#45]
When new version is releasing???

**Comment by andrewebdev** [comment]
@vaibhav-jain unfortunately I have very little time to work on adzone these days. It also turns out that none of my recent projects needed any kind of advertising integration, so there was no need to work on this app at all over the last couple of years.

That said, feel free to fork it and upgrade it yourself, or have a look at some of the other branches if another user already did this :)

**Comment by vaibhav-jain** [comment]
Thanks for the update
